linters:
  fast: true
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - gosec
    - govet
    - misspell
    - nakedret
    - revive
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
