name: "cool"
version: "0.0.1"
usage: "does something cool"
description: "does something cool"
command: "$HELM_BIN list"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh"
useTunnel: true
